#!/bin/bash

interfaces=$(networksetup -listnetworkserviceorder | grep "Hardware")

while read interface
do
	ifconfig $(echo $interface | awk -F'(: )|[)]' '{ print $3 }') 1>/dev/null 2>&1
	if [ "$?" == "0" ]
		then
		if [ $(echo $(echo $(ifconfig $(echo $interface | awk -F'(: )|[)]' '{ print $3 }') | awk -F'status: ' '{ print $2 } '))) == "active" ]
			then
			echo DEVICE: $(echo $interface | awk -F'(: )|[)]' '{ print $3 }')
			echo NAME: $(echo $interface | awk -F'(, )|[:]' '{ print $2 }')
			echo MAC ADDRESS: $(ifconfig $(echo $interface | awk -F'(: )|[)]' '{ print $3 }') | awk -F'ether ' '{ print $2 } ')
			echo IP ADDRESS: $(ipconfig getifaddr $(echo $interface | awk -F'(: )|[)]' '{ print $3 }'))
			echo SUBNET MASK: $(ipconfig getoption $(echo $interface | awk -F'(: )|[)]' '{ print $3 }') subnet_mask)
		fi
	fi
done <<< "$interfaces"